builds:
  - goos:
      - linux
    goarch:
      - amd64
      - 386
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    files:
      - none*
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
